### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sanayasfp** [codergautam/openai-gpt-token-counter#1]
https://github.com/SanaYasfp/openai-gpt-token-counter.git

**Comment by codergautam** [comment]
Should I rewrite the package in typescript to do this?

**Comment by codergautam** [comment]
Oh I saw your repo, please make it a pull request so I can merge into the main package. Also we support a lot more models so pls check that.

**Comment by sanayasfp** [comment]
Just submit a pull request.
Would you mind sharing the list of supported models.

**Comment by codergautam** [comment]
Merged your PR #2 

The list of models are: `["gpt-4", "gpt-4-0613", "gpt-4-32k", "gpt-4-32k-0613", "gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-3.5-turbo-0613", "gpt-3.5-turbo-16k-0613"]`

Hope this helps!

**Comment by codergautam** [comment]
Merged #3
