### ISSUE TITLE
ES6 module import problem

### ISSUE THREAD

**Issue by zalevsk1y** [codergautam/openai-gpt-token-counter#11]
Hello. I had a problem with using the import of this module. When transpiling code with Typescript 4.9, the `import import openaiTokenCounter from 'openai-gpt-token-counter'` was transformed into `const openai_gpt_token_counter_1 = require("openai-gpt-token-counter")["default"]`, which has `undefined` value, because the module was exported using `module.exports`. To solve the problem, i have changed export to `module.exports.default.`

**Comment by codergautam** [comment]
Interesting, so I have to change my export to use module.exports.default instead of module.exports? Or should I export both ways.   I dont want it to cause a breaking change for others.

**Comment by zalevsk1y** [comment]
I figured out. The cause of the problem lies in TypeScript. To fix described situation, you need to specify` "compilerOptions": { "esModuleInterop": true }` in your `tsconfig.json` file. This will fix output code. Sorry for bothering🙂
[https://www.typescriptlang.org/tsconfig#esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop)

**Comment by codergautam** [comment]
No worries at all, glad it's resolved!
