### ISSUE TITLE
Cache the encoder

### ISSUE THREAD

**Issue by xdumstr** [codergautam/openai-gpt-token-counter#4]
https://github.com/codergautam/openai-gpt-token-counter/blob/main/src/index.js#L17

Looks like you are creating the encoder object every time. The encoder object is not cached.  Currently it takes about 100ms to use `chat(messages, model)` method.  In my test, it can reduce the time to <10ms if we cache the encoder. 

Think about the use case, where we use this library to estimate tokens in my chatbot backend.  

Thanks,
Harry

**Comment by x-du** [comment]
https://github.com/codergautam/openai-gpt-token-counter/pull/5

**Comment by codergautam** [comment]
Will be fixed in 1.0.91
