### ISSUE TITLE
Does not work client-side on Next.js v13

### ISSUE THREAD

**Issue by TheRobBrennan** [codergautam/openai-gpt-token-counter#6]
Hi there! I noticed there is an issue where if I try to use this particular module in a Next.js project, it wants to refer to two files that do not exist when the default behavior of running `next dev` or `next build` cleans out the `.next` folder:

- `.next/server/vendor-chunks/encoder.json`
- `.next/server/vendor-chunks/vocab.bpe`

The `vendor-chunks` directory is dynamically cleaned and updated by Next.js - so even manually copying those two files over from `node_modules/openai-gpt-token-counter/src/` fails.

Any suggestions?

**Comment by codergautam** [comment]
Thanks for the issue, will take a look

**Comment by codergautam** [comment]
Unable to reproduce, was able to run on the server.

<img width="1225" alt="image" src="https://github.com/codergautam/openai-gpt-token-counter/assets/66850133/e90433e8-f271-42c5-bbf1-2716f3841e0e">

I don't think the model supports client (webpack) yet, due to upstream dep `tiktoken`. Will see if I can implement in future tho.

**Comment by TheRobBrennan** [comment]
Good morning @codergautam. Wow!!! I am impressed - thank you for the lightning quick reply AND for taking a peek at it so quickly. You are freakin' amazing 🤩

Thinking about it some more, I am stoked to see it works as expected in an API route instead. It's much better than downloading files on the client side with a custom next.config.js configuration or scripts to copy files over.

I updated the title of this PR to reflect that this is something that doesn't work client-side - but that's ok!!

Please feel free to close or resolve this issue. Thank you! ::fist bump::

**Comment by codergautam** [comment]
Thanks! I eventually want to make this a 0 dep model so will do some research and see if I can get webpack and running locally working.
