### ISSUE TITLE
Questions: What is the use of these code? 

### ISSUE THREAD

**Issue by xdumstr** [codergautam/openai-gpt-token-counter#7]
```javascript
    let decodedstrs = []
    for (let token of encoded) {
    var tokenDecoded = (new TextDecoder().decode(encoder.decode([token])));
    decodedstrs.push(tokenDecoded)
```

It seems the `decodedstrs` is never used. 

https://github.com/codergautam/openai-gpt-token-counter/blob/12355f126f473761fc5a909ccaba64b330352203/src/index.js#L40C1-L43C35

**Comment by codergautam** [comment]
It was actually from an example which had that to demonstrate getting tokens as array. Will probably make a new method for getting that info. Thx
