### ISSUE TITLE
You should have mention about the return type Number Or String?

### ISSUE THREAD

**Issue by Rudresh-sisode** [codergautam/openai-gpt-token-counter#8]
In the below if you mention what is the return type of openaiTokenCounter.chat and .text, we as a developer don't need to debug one 
more level.
Please provide your input.
```
const messages = [
  { role: "user", content: "Say this is a test!" },
  // Add more messages if needed
];

const model = "gpt-4"; // Replace with your desired OpenAI chat model

const tokenCount = openaiTokenCounter.chat(messages, model);
console.log(`Token count: ${tokenCount}`);
```

**Comment by codergautam** [comment]
It is number, it is defined in the Types

https://github.com/codergautam/openai-gpt-token-counter/blob/main/src/index.d.ts#L15
