### ISSUE TITLE
Counter has changed

### ISSUE THREAD

**Issue by stephenasuncionDEV** [codergautam/openai-gpt-token-counter#9]
Check `num_tokens_from_messages` code at https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken

**Comment by codergautam** [comment]
Thank you, I will work on this

**Comment by codergautam** [comment]
It hasn't changed, just that guide is new. This function is still accurate. I have updated the example in readme to support the new OpenAI package (functions changed a lot)
